# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-08 15:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_auto_20180119_1708'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='Perfil',
        ),
    ]
