# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-12 21:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0010_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='tipo_moneda',
            field=models.IntegerField(choices=[(1, 'BOLIVIANOS'), (2, 'DOLARES')], default=1),
        ),
    ]
