# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-27 20:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0011_pago_tipo_moneda'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pago',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='participante',
            name='usuario',
        ),
        migrations.AddField(
            model_name='participante',
            name='detalle_deposito',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='participante',
            name='monto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.DeleteModel(
            name='Pago',
        ),
    ]
