# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-29 20:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0013_auto_20180329_1240'),
    ]

    operations = [
        migrations.AddField(
            model_name='participante',
            name='inscripcion',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='portal.Inscripcion'),
        ),
    ]
