# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-09 20:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0015_auto_20180404_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='participante',
            name='material',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='inscripcion',
            name='estado',
            field=models.BooleanField(choices=[(True, 'SI'), (False, 'NO')], default=False),
        ),
        migrations.AlterField(
            model_name='inscripcion',
            name='tipo',
            field=models.IntegerField(choices=[(1, 'SOCIO'), (2, 'DAMA ROTARIA'), (3, 'ROTARACT'), (4, 'SOCIO CONYUGUE')], default=1),
        ),
    ]
