# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-23 02:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0017_participante_credencial'),
    ]

    operations = [
        migrations.AddField(
            model_name='participante',
            name='certificado',
            field=models.BooleanField(default=False),
        ),
    ]
