# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-29 22:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0018_participante_certificado'),
    ]

    operations = [
        migrations.AddField(
            model_name='participante',
            name='cg',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='participante',
            name='ina',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='participante',
            name='pt',
            field=models.BooleanField(default=False),
        ),
    ]
