# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-31 12:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0019_auto_20180529_1817'),
    ]

    operations = [
        migrations.AddField(
            model_name='participante',
            name='ag',
            field=models.BooleanField(choices=[(True, 'SI'), (False, 'NO')], default=False),
        ),
        migrations.AlterField(
            model_name='participante',
            name='certificado',
            field=models.BooleanField(choices=[(True, 'SI'), (False, 'NO')], default=False),
        ),
        migrations.AlterField(
            model_name='participante',
            name='cg',
            field=models.BooleanField(choices=[(True, 'SI'), (False, 'NO')], default=False),
        ),
        migrations.AlterField(
            model_name='participante',
            name='credencial',
            field=models.BooleanField(choices=[(True, 'SI'), (False, 'NO')], default=False),
        ),
        migrations.AlterField(
            model_name='participante',
            name='ina',
            field=models.BooleanField(choices=[(True, 'SI'), (False, 'NO')], default=False),
        ),
        migrations.AlterField(
            model_name='participante',
            name='material',
            field=models.BooleanField(choices=[(True, 'SI'), (False, 'NO')], default=False),
        ),
        migrations.AlterField(
            model_name='participante',
            name='pt',
            field=models.BooleanField(choices=[(True, 'SI'), (False, 'NO')], default=False),
        ),
    ]
